export const navItems = [
  { label: 'Home', path: '/' },
  { label: 'Blog', path: '/blog/' },
  { label: 'Over Jorane', path: '/over-jorane' },
  { label: 'Contact', path: '/contact' },
]

export const categories = [
  { label: 'Alle berichten', path: '/blog/' },
  { label: 'Voor zorgfiguren', path: '/blog/voor-zorgfiguren/' },
  { label: 'Voor leerkrachten', path: '/blog/voor-leerkrachten/' },
  { label: 'Voor zorgverleners', path: '/blog/voor-zorgverleners/' },
]

export const posts = [
  {
    title: 'Blog voor zorgverleners',
    category: 'Voor zorgverleners',
    categoryPath: '/blog/voor-zorgverleners/',
    path: '/blog/blog-voor-zorgverleners',
    image: '/assets/blog-voor-zorgverleners.png',
    foregroundImage: '/assets/zorgverleners.png',
    foregroundClass: 'foreground-zorgverleners',
    age: ['6-9 jaar', '9-12 jaar'],
    theme: ['ernstig ziek', 'ongeneeslijk ziek'],
    goal: ['samen begrijpen', 'samen voelen'],
    intro: 'Een korte testblog voor zorgverleners over hoe je moeilijke informatie rustig en helder kunt aanbieden aan kinderen en hun omgeving.',
  },
  {
    title: 'Blog voor leerkrachten',
    category: 'Voor leerkrachten',
    categoryPath: '/blog/voor-leerkrachten/',
    path: '/blog/blog-voor-leerkrachten',
    image: '/assets/blog-voor-leerkrachten.png',
    foregroundImage: '/assets/leerkrachten.png',
    foregroundClass: 'foreground-leerkrachten',
    age: ['3-5 jaar', '6-9 jaar', '9-12 jaar'],
    theme: ['afscheid en rouw'],
    goal: ['samen begrijpen', 'samen doen'],
    intro: 'Een testblog voor leerkrachten met handvatten om ruimte te maken voor vragen, stilte en gesprek in de klas.',
  },
  {
    title: 'Blog voor zorgfiguren',
    category: 'Voor zorgfiguren',
    categoryPath: '/blog/voor-zorgfiguren/',
    path: '/blog/blog-voor-zorgfiguren',
    image: '/assets/blog-voor-zorgfiguren.png',
    foregroundImage: '/assets/zorgfiguren.png',
    foregroundClass: 'foreground-zorgfiguren',
    age: ['0-2 jaar', '3-5 jaar', '6-9 jaar'],
    theme: ['ernstig ziek', 'ongeneeslijk ziek', 'afscheid en rouw'],
    goal: ['samen begrijpen', 'samen voelen', 'samen doen'],
    intro: 'Een testblog voor zorgfiguren over nabij blijven, woorden zoeken en samen kleine momenten van betekenis maken.',
  },
  {
    title: 'Wanneer woorden moeilijk zijn',
    category: 'Voor zorgfiguren',
    categoryPath: '/blog/voor-zorgfiguren/',
    path: '/blog/wanneer-woorden-moeilijk-zijn',
    image: '/assets/blog-voor-zorgfiguren.png',
    foregroundImage: '/assets/zorgfiguren.png',
    foregroundClass: 'foreground-zorgfiguren',
    age: ['3-5 jaar', '6-9 jaar'],
    theme: ['ernstig ziek'],
    goal: ['samen voelen', 'samen begrijpen'],
    intro: 'Soms zijn er geen perfecte woorden. Deze testblog verkent hoe nabijheid, eenvoud en herhaling toch veiligheid kunnen geven.',
  },
  {
    title: 'Een rustig afscheidsmoment maken',
    category: 'Voor zorgfiguren',
    categoryPath: '/blog/voor-zorgfiguren/',
    path: '/blog/een-rustig-afscheidsmoment-maken',
    image: '/assets/blog-voor-zorgfiguren.png',
    foregroundImage: '/assets/zorgfiguren.png',
    foregroundClass: 'foreground-zorgfiguren',
    age: ['0-2 jaar', '3-5 jaar'],
    theme: ['afscheid en rouw'],
    goal: ['samen voelen', 'samen doen'],
    intro: 'Een testblog over zachte rituelen, voorspelbaarheid en kleine handelingen die een afscheid tastbaar kunnen maken.',
  },
  {
    title: 'Praten in de klas over ziekte',
    category: 'Voor leerkrachten',
    categoryPath: '/blog/voor-leerkrachten/',
    path: '/blog/praten-in-de-klas-over-ziekte',
    image: '/assets/blog-voor-leerkrachten.png',
    foregroundImage: '/assets/leerkrachten.png',
    foregroundClass: 'foreground-leerkrachten',
    age: ['6-9 jaar', '9-12 jaar'],
    theme: ['ernstig ziek'],
    goal: ['samen begrijpen'],
    intro: 'Deze testblog laat zien hoe je als leerkracht ziekte bespreekbaar kunt maken zonder de klas te overspoelen.',
  },
  {
    title: 'Rituelen die kinderen houvast geven',
    category: 'Voor leerkrachten',
    categoryPath: '/blog/voor-leerkrachten/',
    path: '/blog/rituelen-die-kinderen-houvast-geven',
    image: '/assets/blog-voor-leerkrachten.png',
    foregroundImage: '/assets/leerkrachten.png',
    foregroundClass: 'foreground-leerkrachten',
    age: ['3-5 jaar', '6-9 jaar'],
    theme: ['afscheid en rouw'],
    goal: ['samen doen', 'samen voelen'],
    intro: 'Een testblog over klasrituelen die kinderen helpen om gevoelens te delen en samen houvast te vinden.',
  },
  {
    title: 'Uitleg geven zonder te overspoelen',
    category: 'Voor zorgverleners',
    categoryPath: '/blog/voor-zorgverleners/',
    path: '/blog/uitleg-geven-zonder-te-overspoelen',
    image: '/assets/blog-voor-zorgverleners.png',
    foregroundImage: '/assets/zorgverleners.png',
    foregroundClass: 'foreground-zorgverleners',
    age: ['6-9 jaar', '9-12 jaar'],
    theme: ['ongeneeslijk ziek'],
    goal: ['samen begrijpen'],
    intro: 'Een testblog met aandacht voor doseren, checken wat een kind al weet en aansluiten bij de taal van het gezin.',
  },
  {
    title: 'Samen iets doen na slecht nieuws',
    category: 'Voor zorgverleners',
    categoryPath: '/blog/voor-zorgverleners/',
    path: '/blog/samen-iets-doen-na-slecht-nieuws',
    image: '/assets/blog-voor-zorgverleners.png',
    foregroundImage: '/assets/zorgverleners.png',
    foregroundClass: 'foreground-zorgverleners',
    age: ['0-2 jaar', '3-5 jaar', '6-9 jaar'],
    theme: ['ernstig ziek', 'ongeneeslijk ziek'],
    goal: ['samen doen', 'samen voelen'],
    intro: 'Een testblog over eenvoudige activiteiten na slecht nieuws: tekenen, verzamelen, vertellen of gewoon samen zijn.',
  },
]

export const defaultFilterGroups = [
  {
    key: 'age',
    label: 'Leeftijd',
    options: ['0-2 jaar', '3-5 jaar', '6-9 jaar', '9-12 jaar'],
  },
  {
    key: 'theme',
    label: 'Thema',
    options: ['ernstig ziek', 'ongeneeslijk ziek', 'afscheid en rouw'],
  },
  {
    key: 'goal',
    label: 'Doel',
    options: ['samen begrijpen', 'samen voelen', 'samen doen'],
  },
]

export const homeTiles = [
  { path: '/blog/voor-zorgfiguren/', image: '/assets/voor-zorgfiguren.png', alt: 'Voor zorgfiguren' },
  { path: '/blog/voor-leerkrachten/', image: '/assets/voor-leerkrachten.png', alt: 'Voor leerkrachten' },
  { path: '/blog/voor-zorgverleners/', image: '/assets/voor-zorgverleners.png', alt: 'Voor zorgverleners' },
  { path: '/contact', image: '/assets/contact-card.png', alt: 'Contact' },
]

export const defaultSiteContent = {
  home: {
    pageKey: 'home',
    title: 'Warme taal voor moeilijke momenten',
    body: 'Verhalen, handvatten en zachte oefeningen voor kinderen, zorgfiguren, leerkrachten en zorgverleners wanneer ziekte, afscheid of rouw dichtbij komt.',
  },
  about: {
    pageKey: 'about',
    title: 'Ruimte maken voor wat moeilijk te zeggen is',
    body: [
      'Met Mee in het verhaal wil Jorane kinderen en de mensen rondom hen helpen om taal, rust en houvast te vinden wanneer ziekte, afscheid of rouw dichtbij komt.',
      'Moeilijke gebeurtenissen komen vaak met grote vragen. Wat zeg je tegen een kind? Hoe blijf je eerlijk zonder te overspoelen? En hoe geef je ruimte aan verdriet, verwarring of stilte?',
      'Deze plek verzamelt zachte woorden, concrete handvatten en kleine oefeningen voor zorgfiguren, leerkrachten en zorgverleners die kinderen nabij willen blijven op kwetsbare momenten.',
    ].join('\n\n'),
  },
}

export const defaultArticle = {
  title: '',
  category: 'Voor zorgfiguren',
  intro: '',
  content: '',
  age: [],
  theme: [],
  goal: [],
}
